shortTitle: "Glowing"
title: "Glowing - Bootstrap 5 HTML Templates"
baseURL: "http://localhost:9001/"
disableKinds: ["section", "taxonomy", "term", "RSS", "sitemap", "robotsTXT", "404"]
publishDir: "dist"
relativeURLs: true
uglyurls: true
refLinksErrorLevel: warning
refLinksNotFoundURL: "/../404.html"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
    tableOfContents:
        startLevel: 2
        endLevel: 3

security:
    enableInlineShortcodes: true
    funcs:
        getenv:
            - ^HUGO_
            - NETLIFY
    exec:
        allow:
            - ^dart-sass-embedded$
            - ^go$
            - ^npx$
            - ^postcss$
            - ^babel$
module:
    mounts:
        -   source: src/content
            target: content
        -   source: src/static
            target: static
        -   source: src/layouts
            target: layouts
        -   source: src/data
            target: data
        -   source: src/assets
            target: assets
outputs:
    home:
        - HTML
        - JSON

params:
    siteName: Glowing
    demoUrl: "https://glowing.g5plus.net/main/"
    enableDarkMode: true
    cdn:
      # See https://www.srihash.org for info on how to generate the hashes
      css:              "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      css_hash:         "sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      js:               "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
      js_hash:          "sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
      js_bundle:        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      js_bundle_hash:   "sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
